---

- hosts: tag_Role_dockerhost
  become: true
  tasks:
  - name: Wait for port ssh to become open on the host, don't start checking for 10 seconds
    ansible.builtin.wait_for:
      port: 22
      delay: 5

  - name: Install Docker Agent
    ansible.builtin.package:
      name: docker
      state: present

  - name: Start the Docker service
    ansible.builtin.service:
      name: docker
      state: started
      enabled: yes
      
  - name: Add user to docker admin
    command: "usermod -a -G docker ec2-user"
    ignore_errors: yes

  - name: Delete running container
    command: docker stop regapp-server
    ignore_errors: yes

  - name: Remove the container
    command: docker rm regapp-server
    ignore_errors: yes

  - name: Delete old image
    command: docker rmi vicky210/regapp:latest
    ignore_errors: yes

  - name: create container
    command: docker run -d --name regapp-server -p 8088:8080 vicky210/regapp:latest
