---
- hosts: localhost
  tasks:
  - name: Create docker image
    command: docker build -t regapp:latest .

  - name: Create tag to push to Dockerhub
    command: docker tag regapp:latest vicky210/regapp:latest

  - name: Push the docker image to Dockerhub
    command: docker push vicky210/regapp:latest
