---
- hosts: dockerhost

  tasks:
  - name: Delete running container
    command: docker stop regapp-server
    ignore_errors: yes

  - name: Remove the container
    command: docker rm regapp-server
    ignore_errors: yes

  - name: Delete old image
    command: docker rmi vicky210/regapp:latest
    ignore_errors: yes

  - name: create container
    command: docker run -d --name regapp-server -p 8088:8080 vicky210/regapp:latest
